### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by scott-rothman** [jakemmarsh/react-rocket-boilerplate#31]
Just ran through the initial install and installed gulp globally

Attempted to run `gulp dev` and got the following error

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at loader (/home/scott/Sites/helppat-scottr/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/scott/Sites/helppat-scottr/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)

**Comment by jakemmarsh** [comment]
I'm unable to replicate this locally. Did you see `Requiring external module babel-core/register` when you first ran the Gulp task? It should be automatically loading babel to parse any further code as ES6

**Comment by MacgyverMartins** [comment]
@scott-rothman be sure that file `.babelrc` is in your root directory.

**Comment by scott-rothman** [comment]
@MacgyverMartins Think this was the issue, thanks!
